const messages=document.querySelector("#messages"),form=document.querySelector("#chatForm"),input=document.querySelector("#messageInput"),clearChat=document.querySelector("#clearChat"),micButton=document.querySelector("#micButton"),voiceStatus=document.querySelector("#voiceStatus"),memoryKey="jarvis-conversation";
const cannedReplies=[{match:["diagnostic","system check","status"],reply:"Running a full diagnostic now. Core temperature is nominal, memory integrity is 100%, network latency is 24 milliseconds, and all primary systems are operational. You are cleared for launch."},{match:["briefing","today","news"],reply:"Your briefing is ready: focus on one important outcome, protect your attention, and leave room for the unexpected. I can connect to live services once you add an AI provider and API integrations."},{match:["what can you do","capabilities","help"],reply:"I can hold a conversation, remember this local session, respond to quick protocols, listen through your microphone, and speak replies aloud. With a secure backend, I can also connect calendars, smart-home controls, search, and custom tools."},{match:["hello","hi","hey"],reply:"Good to see you. All systems are online and waiting for your command."},{match:["time"],reply:`The local system clock reads ${new Intl.DateTimeFormat([], {hour:"numeric",minute:"2-digit"}).format(new Date())}.`}];
function addMessage(text,role="assistant",save=true){const item=document.createElement("div");item.className=`message ${role}`;item.innerHTML=role==="assistant"?`<div class="avatar">J</div><div class="message-bubble"><div class="message-label">JARVIS // ONLINE</div>${escapeHtml(text)}</div>`:`<div class="message-bubble"><div class="message-label">YOU</div>${escapeHtml(text)}</div>`;messages.append(item);messages.scrollTop=messages.scrollHeight;if(save)localStorage.setItem(memoryKey,messages.innerHTML)}
function escapeHtml(value){return value.replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[character]))}
function replyTo(text){const normalized=text.toLowerCase().trim(),found=cannedReplies.find(({match})=>match.some(term=>term.includes(" ") ? normalized.includes(term) : new RegExp(`\\b${term}\\b`).test(normalized)));return found?.reply||`I have logged your request: “${text}”. My conversational core is ready, but live intelligence requires an AI provider connection. For now, try “run a diagnostic”, “daily briefing”, or “what can you do?”.`}
function submitMessage(text){const cleanText=text.trim();if(!cleanText)return;addMessage(cleanText,"user");input.value="";window.setTimeout(()=>{const response=replyTo(cleanText);addMessage(response);speak(response)},450)}
function speak(text){if(!("speechSynthesis"in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.rate=.94;utterance.pitch=.8;utterance.volume=.8;window.speechSynthesis.speak(utterance)}
function restoreConversation(){const saved=localStorage.getItem(memoryKey);if(saved)messages.innerHTML=saved;else addMessage("Good evening. I am JARVIS, your personal intelligence interface. All systems are online. How may I assist you?","assistant");messages.scrollTop=messages.scrollHeight}
form.addEventListener("submit",event=>{event.preventDefault();submitMessage(input.value)});document.querySelectorAll("[data-prompt]").forEach(button=>button.addEventListener("click",()=>submitMessage(button.dataset.prompt)));clearChat.addEventListener("click",()=>{localStorage.removeItem(memoryKey);messages.innerHTML="";restoreConversation()});
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(SpeechRecognition){const recognition=new SpeechRecognition();recognition.lang="en-US";recognition.interimResults=false;recognition.onstart=()=>{micButton.classList.add("listening");voiceStatus.textContent="LISTENING"};recognition.onend=()=>{micButton.classList.remove("listening");voiceStatus.textContent="READY"};recognition.onresult=event=>{input.value=event.results[0][0].transcript;submitMessage(input.value)};recognition.onerror=()=>{voiceStatus.textContent="READY"};micButton.addEventListener("click",()=>recognition.start())}else{micButton.title="Voice input is not supported in this browser";micButton.addEventListener("click",()=>addMessage("Voice input is not supported by this browser. Try Chrome or Edge for microphone controls.","assistant"))}restoreConversation();
